apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: simple-nodejs-app-uxjj
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-giko-tenant/nodejs-users/simple-nodejs-app-uxjj@sha256:9c91c1f4b4b0a33ab71496f8a854724517d7f0b5943f3defcf95c1a0632bac5e
        name: my-nodejs
        resources: {}
status: {}
